# Generated by Django 4.2.7 on 2024-01-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coordinator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charity_name', models.CharField(help_text='required, max length 50 characters', max_length=50, verbose_name='Charity Name')),
                ('charity_description', models.TextField(verbose_name='Charity Description')),
                ('charities_coordinators', models.ManyToManyField(help_text='Hold control and click to select multiple', related_name='CharityProfiles', to='coordinator.coordinatorprofile', verbose_name='coordinators associated with charity')),
            ],
        ),
    ]
