# Generated by Django 4.2.7 on 2023-12-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('charity', '0001_initial'),
        ('coordinator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charityprofile',
            name='charities_coordinators',
            field=models.ManyToManyField(to='coordinator.coordinatorprofile', verbose_name='coordinators associated with charity'),
        ),
    ]
