# Generated by Django 4.2.7 on 2024-01-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0001_initial'),
        ('charity', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charityprofile',
            name='charities_coordinators',
            field=models.ManyToManyField(related_name='CharityProfiles+', to='coordinator.coordinatorprofile', verbose_name='coordinators associated with charity'),
        ),
    ]
