# Generated by Django 4.2.7 on 2024-01-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0002_alter_coordinatorprofile_coordinators_charities'),
        ('charity', '0003_alter_charityprofile_charities_coordinators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charityprofile',
            name='charities_coordinators',
            field=models.ManyToManyField(related_name='CharityProfiles', to='coordinator.coordinatorprofile', verbose_name='coordinators associated with charity'),
        ),
    ]
