# Generated by Django 4.2.7 on 2024-01-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0006_alter_coordinatorprofile_fname_and_more'),
        ('charity', '0004_alter_charityprofile_charities_coordinators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charityprofile',
            name='charities_coordinators',
            field=models.ManyToManyField(help_text='Hold control and click to select multiple', related_name='CharityProfiles', to='coordinator.coordinatorprofile', verbose_name='coordinators associated with charity'),
        ),
        migrations.AlterField(
            model_name='charityprofile',
            name='charity_name',
            field=models.CharField(help_text='required, max length 50 characters', max_length=50, verbose_name='Charity Name'),
        ),
    ]
