# Generated by Django 4.2.7 on 2023-12-20 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordinatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(help_text='format: required, max_length=50', max_length=50, verbose_name='First Name')),
                ('lname', models.CharField(help_text='format: required, max_length=50', max_length=50, verbose_name='Last Name')),
                ('activated', models.BooleanField(default=False)),
                ('coordinators_charities', models.ManyToManyField(to='charity.charityprofile', verbose_name='coordinators associated charities')),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(verbose_name='Notes on activity')),
                ('coordinator', models.ManyToManyField(to='coordinator.coordinatorprofile', verbose_name='Coordinator')),
                ('volunteer', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Volunteer')),
            ],
        ),
    ]
