# Generated by Django 4.2.7 on 2024-01-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0003_alter_charityprofile_charities_coordinators'),
        ('coordinator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinatorprofile',
            name='coordinators_charities',
            field=models.ManyToManyField(related_name='CoordinatorProfiles+', to='charity.charityprofile', verbose_name='coordinators associated charities'),
        ),
    ]
