# Generated by Django 4.2.7 on 2023-12-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinatorprofile',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
