# Generated by Django 4.2.7 on 2024-01-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0004_alter_charityprofile_charities_coordinators'),
        ('coordinator', '0002_alter_coordinatorprofile_coordinators_charities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinatorprofile',
            name='coordinators_charities',
            field=models.ManyToManyField(related_name='CoordinatorProfiles', to='charity.charityprofile', verbose_name='coordinators associated charities'),
        ),
    ]
