# Generated by Django 4.2.7 on 2024-01-06 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0003_alter_coordinatorprofile_coordinators_charities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinatorprofile',
            name='coordinators_charities',
        ),
    ]
