# Generated by Django 4.2.7 on 2024-01-21 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0004_remove_coordinatorprofile_coordinators_charities'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChooseCoordinator',
        ),
    ]
