# Generated by Django 4.2.7 on 2024-01-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinator', '0005_delete_choosecoordinator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinatorprofile',
            name='fname',
            field=models.CharField(help_text='required, max length 50 characters', max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='coordinatorprofile',
            name='lname',
            field=models.CharField(help_text='required, max length 50 characters', max_length=50, verbose_name='Last Name'),
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
