# Generated by Django 4.2.7 on 2024-01-21 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='name',
        ),
    ]
