# Generated by Django 4.2.7 on 2023-12-24 15:11

import cloudinary.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('fname', models.CharField(help_text='format: required, max_length=50', max_length=50, verbose_name='First Name')),
                ('lname', models.CharField(help_text='format: required, max_length=50', max_length=50, verbose_name='Last Name')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=12, region=None)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('profile_picture', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('special_skills_description', models.TextField(blank=True, verbose_name='special skills description')),
                ('activated', models.BooleanField(default=False)),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('time_length_hours', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(168)])),
                ('time_length_days', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(7)])),
                ('section_of_day', models.IntegerField(choices=[(0, 'None'), (1, 'Morning'), (2, 'Afternoon'), (3, 'Evening')], default=0)),
                ('day', models.IntegerField(choices=[(0, 'None'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=0)),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('skilled', models.ManyToManyField(related_name='choices', to='volunteer.skillchoices', verbose_name='skills')),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
