# Generated by Django 4.2.7 on 2024-01-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeperiod',
            name='fri_am',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeperiod',
            name='fri_ev',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeperiod',
            name='fri_pm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeperiod',
            name='mon_am',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeperiod',
            name='mon_ev',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeperiod',
            name='mon_pm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeperiod',
            name='sat_am',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeperiod',
            name='sat_ev',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeperiod',
            name='sat_pm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeperiod',
            name='sum_pm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeperiod',
            name='sun_am',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeperiod',
            name='sun_ev',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeperiod',
            name='thu_am',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeperiod',
            name='thu_ev',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeperiod',
            name='thu_pm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeperiod',
            name='tue_am',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeperiod',
            name='tue_ev',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeperiod',
            name='tue_pm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeperiod',
            name='wed_am',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeperiod',
            name='wed_ev',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeperiod',
            name='wed_pm',
            field=models.BooleanField(default=False),
        ),
    ]
