# Generated by Django 4.2.7 on 2024-01-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='skilled',
            field=models.ManyToManyField(related_name='Skills', to='volunteer.skillchoices', verbose_name='skills'),
        ),
    ]
