# Generated by Django 4.2.7 on 2024-01-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerprofile',
            name='fname',
            field=models.CharField(help_text='This is required and has a maximum length of 50 characters', max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='lname',
            field=models.CharField(help_text='This is required and has a maximum length of 50 characters', max_length=50, verbose_name='Last Name'),
        ),
    ]
