# Generated by Django 4.2.7 on 2023-12-18 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillchoices',
            name='choice_link',
        ),
    ]
