# Generated by Django 4.2.7 on 2023-12-08 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='skills',
            new_name='time_link',
        ),
    ]
