# Generated by Django 4.2.7 on 2023-11-27 11:43

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerprofile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=12, region=None),
        ),
    ]
