# Generated by Django 4.2.7 on 2024-01-04 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_timeperiod_fri_am_timeperiod_fri_ev_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeperiod',
            old_name='sum_pm',
            new_name='sun_pm',
        ),
    ]
