# Generated by Django 4.2.7 on 2023-11-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_alter_volunteerprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='skills',
            field=models.ManyToManyField(choices=[('AD', 'ADMINISTRATION'), ('CO', 'COMPANIONSHIP'), ('DI', 'DIY'), ('DR', 'DRIVING'), ('EV', 'EVENTS'), ('EN', 'ENVIRONMENTAL'), ('FU', 'FUNDRAISING'), ('GA', 'GARDENING'), ('RE', 'READING'), ('SH', 'SHOPPING'), ('TU', 'TUTORING')], to='volunteer.skills'),
        ),
    ]
