# Generated by Django 4.2.7 on 2024-01-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_alter_skills_skilled'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillchoices',
            name='profile',
            field=models.ManyToManyField(related_name='SkillChoices', to='volunteer.skills', verbose_name='skilled'),
        ),
    ]
