# Generated by Django 4.2.7 on 2023-12-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_remove_skillchoices_choice_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='skilled',
            field=models.ManyToManyField(related_name='choices', to='volunteer.skillchoices', verbose_name='skills'),
        ),
    ]
