# Generated by Django 4.2.7 on 2024-01-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_alter_volunteerprofile_fname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerprofile',
            name='special_skills_description',
            field=models.TextField(blank=True, help_text='Provide us with information about your skills here', max_length=500, verbose_name='Information'),
        ),
    ]
