# Generated by Django 4.2.7 on 2023-11-28 10:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('volunteer', '0003_alter_skills_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeperiod',
            name='day',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=0),
        ),
        migrations.AddField(
            model_name='timeperiod',
            name='section_of_day',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Morning'), (2, 'Afternoon'), (3, 'Evening')], default=0),
        ),
        migrations.AddField(
            model_name='timeperiod',
            name='time_length_days',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AddField(
            model_name='timeperiod',
            name='time_length_hours',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(168)]),
        ),
        migrations.AddField(
            model_name='timeperiod',
            name='user_name',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
