# Generated by Django 4.2.7 on 2023-11-29 11:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('volunteer', '0005_rename_timeperiod_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Time',
            new_name='TimePeriod',
        ),
        migrations.AlterField(
            model_name='skills',
            name='skills',
            field=models.ManyToManyField(choices=[('1', 'ADMINISTRATION'), ('2', 'COMPANIONSHIP'), ('3', 'DIY'), ('4', 'DRIVING'), ('5', 'EVENTS'), ('6', 'ENVIRONMENTAL'), ('7', 'FUNDRAISING'), ('8', 'GARDENING'), ('9', 'READING'), ('10', 'SHOPPING'), ('11', 'TUTORING')], to='volunteer.skills'),
        ),
    ]
