# Generated by Django 4.2.7 on 2024-01-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0005_alter_timeperiod_fri_am_alter_timeperiod_fri_ev_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeperiod',
            name='mon_am',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
