# Generated by Django 4.2.7 on 2024-01-06 11:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0006_alter_timeperiod_mon_am_alter_volunteerprofile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerprofile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='fri_am',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='fri_ev',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='fri_pm',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='mon_am',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='mon_ev',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='mon_pm',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='sat_am',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='sat_ev',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='sat_pm',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='sun_am',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='sun_ev',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='sun_pm',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='thu_am',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='thu_ev',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='thu_pm',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='time_length_days',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='time_length_hours',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(168)]),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='tue_am',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='tue_ev',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='tue_pm',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='wed_am',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='wed_ev',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='wed_pm',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Wednesday Afternoon'),
        ),
        migrations.DeleteModel(
            name='TimePeriod',
        ),
    ]
