# Generated by Django 4.2.7 on 2023-11-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0006_rename_time_timeperiod_alter_skills_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='skilled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='skills',
            name='skills',
            field=models.ManyToManyField(choices=[('1', 'ADMINISTRATION'), ('2', 'COMPANIONSHIP'), ('3', 'DIY'), ('4', 'DRIVING'), ('5', 'EVENTS'), ('6', 'ENVIRONMENTAL'), ('7', 'FUNDRAISING'), ('8', 'GARDENING'), ('9', 'READING'), ('10', 'SHOPPING'), ('11', 'TUTORING')], to='volunteer.volunteerprofile'),
        ),
    ]
