# Generated by Django 4.2.7 on 2024-01-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0007_remove_volunteerprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='skilled',
            field=models.ManyToManyField(related_name='VolunteerProfiles', to='volunteer.skillchoices', verbose_name='Skill Options'),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='mon_am',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
