# Generated by Django 4.2.7 on 2023-11-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0007_skilled_alter_skills_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='skills',
            field=models.ManyToManyField(choices=[('1', 'ADMINISTRATION'), ('2', 'COMPANIONSHIP'), ('3', 'DIY'), ('4', 'DRIVING'), ('5', 'EVENTS'), ('6', 'ENVIRONMENTAL'), ('7', 'FUNDRAISING'), ('8', 'GARDENING'), ('9', 'READING'), ('10', 'SHOPPING'), ('11', 'TUTORING')], to='volunteer.skills'),
        ),
    ]
